[package]
name = "brawl_hub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.17.1"
tokio = { version = "1", features = ["full"] }
thirtyfour = "0.31.0"
futures = "0.3.28"